version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: "node/default"
    steps:
      - checkout
      - run: npm init --yes
      - node/with-cache:
          steps:
            - run: npm i create-elm-app
            - run: npx elm-app test

workflows:
  build-and-test:
    jobs:
      - build-and-test
